# config.yaml

# Programs to target for booking
target_program:
  - "Level 2 Open Play"
  - "Level 3 Open Play"

# Desired booking time range
target_times:
  - "6:00 PM - 9:00 PM"
  - "6:00 PM - 9:00 PM"
  - "6:00 PM - 9:00 PM"
  - "6:00 PM - 9:00 PM"
  - "6:00 PM - 9:00 PM"
  - "10:00 AM - 6:00 PM"
  - "10:00 AM - 6:00 PM"

add_to_waitlist: "False"

rest_days: 
  - "Sun"
